import { ChannelType } from "../constants/channel";
import { MessageType } from "../constants/message";
import Channel from "../types/Channel";

export const channelData: Channel[] = [
    {
        id: "4c0b8918-edd9-4c8e-9eac-ea9769c98aae",
        name: "Phạm Việt Tú",
        type: ChannelType.SINGLE_TYPE,
        avatars: [
            "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
        ],
        recordStatus: null,
        read: true,
        online: false,
        message: {
            type: MessageType.MESSAGE,
            recordStatus: "",
            message: "Hello",
            subMessage: "",
            iconMessage: "",
            timeOfMessageSentDisplay: "12:30",
            channelID: "1c0b8918-edd9-4c8e-9eac-ea9769c98aae",
        },
        readers: [],
        unreadCounter: 0,
        sort: "",
        keywords: "",
    },
    {
        id: "5d1a8918-edd9-4c8e-9eac-ea9769c98aaf",
        name: "Dev",
        type: ChannelType.GROUP_TYPE,
        avatars: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Tabby_cat_with_blue_eyes-3336579.jpg/1705px-Tabby_cat_with_blue_eyes-3336579.jpg",
            "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
        ],
        recordStatus: null,
        read: true,
        online: true,
        message: {
            type: MessageType.ICON_MESSAGE,
            recordStatus: "",
            message: "",
            subMessage: "",
            iconMessage: "👍",
            timeOfMessageSentDisplay: "Vừa xong",
            channelID: "1c0b8918-edd9-4c8e-9eac-ea9769c98aaf",
        },
        readers: [],
        unreadCounter: 0,
        sort: "",
        keywords: "",
    },
    {
        id: "6e2b8918-edd9-4c8e-9ac-ea9769c98ab0",
        name: "Dog",
        type: ChannelType.SINGLE_TYPE,
        avatars: [
            "https://img.freepik.com/free-photo/isolated-happy-smiling-dog-white-background-portrait-4_1562-693.jpg",
        ],
        recordStatus: null,
        read: false,
        online: false,
        message: {
            type: MessageType.ATTACHMENTS,
            recordStatus: "",
            message: "Let's meet up!",
            subMessage: "",
            iconMessage: "",
            timeOfMessageSentDisplay: "2 phút trước",
            channelID: "1c0b8918-edd9-4c8e-9eac-ea9769c98ab0",
        },
        readers: [],
        unreadCounter: 1,
        sort: "",
        keywords: "",
    },
    {
        id: "7f3c8918-edd9-4c8e-9eac-ea9769c98ab1",
        name: "John Wick",
        type: ChannelType.SINGLE_TYPE,
        avatars: [
            "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_FMjpg_UX1000_.jpg",
        ],
        recordStatus: null,
        read: false,
        online: true,
        message: {
            type: MessageType.MESSAGE,
            recordStatus: "",
            message: "Are you to the party?",
            subMessage: "",
            iconMessage: "",
            timeOfMessageSentDisplay: "05-06-2024 10:30",
            channelID: "1c0b8918-edd9-4c8e-9eac-ea9769c98ab1",
        },
        readers: [],
        unreadCounter: 2,
        sort: "",
        keywords: "",
    },
    {
        id: "8g4d8918-edd9-4c8e-9eac-ea9769c98ab2",

        name: "Taylor swift",
        type: ChannelType.SINGLE_TYPE,
        avatars: [
            "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
        ],
        recordStatus: null,
        read: false,
        online: false,
        message: {
            type: MessageType.MESSAGE,
            recordStatus: "",
            message: "Good night!",
            subMessage: "",
            iconMessage: "",
            timeOfMessageSentDisplay: "5 giây trước",
            channelID: "1c0b8918-edd9-4c8e-9eac-ea9769c98ab2",
        },
        readers: [],
        unreadCounter: 10,
        sort: "",
        keywords: "",
    },
];
