import User from "../types/User";

export const friendData: User[] = [
    {
        id: "b16d2fc4-2e57-4802-aecc-537f7a873f75",
        fullName: "Phạm Việt Tú",
        avatar: "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
        online: true,
        coverPhoto:
            "https://images.pexels.com/photos/1366919/pexels-photo-1366919.jpeg?auto=compress&cs=tinysrgb&w=800",
        gender: "Male",
        dob: "10-05-1998",
        phone: "0946841587",
        email: "phamviettu3009@gmail.com",
        countryCode: "+84",
        languageCode: "vi",
        setting: {
            publicEmail: false,
            publicGender: false,
            publicPhone: false,
            publicDob: false,
        },
    },
    {
        id: "4c9b5fef-57e3-4291-acaf-cfd7a3af8e07",
        fullName: "Dev",
        avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Tabby_cat_with_blue_eyes-3336579.jpg/1705px-Tabby_cat_with_blue_eyes-3336579.jpg",
        online: true,
        coverPhoto:
            "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg?auto=compress&cs=tinysrgb&w=800",
        gender: "Male",
        dob: "30-09-1999",
        phone: "0946841587",
        email: "viettu3009@gmail.com",
        countryCode: "+84",
        languageCode: "vi",
        setting: {
            publicEmail: false,
            publicGender: false,
            publicPhone: false,
            publicDob: false,
        },
    },
    {
        id: "4c9b5fef-57e3-4291-acaf-cfd7a3af8e01",
        fullName: "John Wick",
        avatar: "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_FMjpg_UX1000_.jpg",
        online: false,
        coverPhoto:
            "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg?auto=compress&cs=tinysrgb&w=800",
        gender: "Male",
        dob: "30-09-1999",
        phone: "0946841587",
        email: "viettu@gmail.com",
        countryCode: "+84",
        languageCode: "vi",
        setting: {
            publicEmail: false,
            publicGender: false,
            publicPhone: false,
            publicDob: false,
        },
    },
    {
        id: "4c9b5fef-57e3-4291-acaf-cfd7a3af8e02",
        fullName: "Dog",
        avatar: "https://img.freepik.com/free-photo/isolated-happy-smiling-dog-white-background-portrait-4_1562-693.jpg",
        online: false,
        coverPhoto:
            "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg?auto=compress&cs=tinysrgb&w=800",
        gender: "Male",
        dob: "30-09-1999",
        phone: "0946841587",
        email: "viettu@gmail.com",
        countryCode: "+84",
        languageCode: "vi",
        setting: {
            publicEmail: false,
            publicGender: false,
            publicPhone: false,
            publicDob: false,
        },
    },
    {
        id: "4c9b5fef-57e3-4291-acaf-cfd7a3af8e03",
        fullName: "Taylor swift",
        avatar: "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
        online: false,
        coverPhoto:
            "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg?auto=compress&cs=tinysrgb&w=800",
        gender: "Female",
        dob: "30-09-1999",
        phone: "0946841587",
        email: "viettu@gmail.com",
        countryCode: "+84",
        languageCode: "vi",
        setting: {
            publicEmail: false,
            publicGender: false,
            publicPhone: false,
            publicDob: false,
        },
    },
];
