import { AttachmentType } from "../constants/attachment";
import { MessageRecordStatus, MessageType } from "../constants/message";
import Message from "../types/Message";

export const messageData: Message[] = [
    {
        id: "d3576bc0-f13e-4c40-a7ed-7e00559ce31e",
        type: MessageType.MESSAGE,
        message: "hello?",
        subMessage: null,
        iconMessage: null,
        messageOnRightSide: false,
        consecutiveMessages: false,
        timeOfMessageSentDisplay: "11/08/2024 14:30",
        edited: false,
        makerDate: "Fri Jun 17 2022 11:27:28 GMT+0100",
        recordStatus: null,
        channelID: "f4536349-e139-4eae-b3e1-4811f9cc6329",
        reply: null,
        attachments: null,
        messageReactions: null,
        user: {
            id: "42b73dae-321f-4258-a604-afad0839b11f",
            fullName: "Taylor swift",
            avatar: "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            online: true,
            coverPhoto:
                "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            gender: "Female",
            dob: "1723362246",
            phone: "0987654321",
            email: "taylor.swift@gmail.com",
            countryCode: "+1",
            languageCode: "en",
            setting: {
                publicEmail: false,
                publicGender: false,
                publicPhone: false,
                publicDob: false,
            },
        },
        sync: false,
        syncID: null,
        unsent: false,
        urlsPreview: null,
    },

    {
        id: "d3576bc0-f13e-4c40-a7ed-7e00559ce35t",
        type: MessageType.MESSAGE,
        message: "hello?",
        subMessage: null,
        iconMessage: null,
        messageOnRightSide: false,
        consecutiveMessages: true,
        timeOfMessageSentDisplay: "11/08/2024 14:30",
        edited: false,
        makerDate: "Fri Jun 17 2022 11:27:28 GMT+0100",
        recordStatus: null,
        channelID: "f4536349-e139-4eae-b3e1-4811f9cc6329",
        reply: null,
        attachments: null,
        messageReactions: [
            {
                icon: "👍",
                quantity: 1,
                toOwn: false,
            },
            {
                icon: "❤",
                quantity: 1,
                toOwn: true,
            },
        ],
        user: {
            id: "42b73dae-321f-4258-a604-afad0839b11f",
            fullName: "Taylor swift",
            avatar: "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            online: true,
            coverPhoto:
                "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            gender: "Female",
            dob: "1723362246",
            phone: "0987654321",
            email: "taylor.swift@gmail.com",
            countryCode: "+1",
            languageCode: "en",
            setting: {
                publicEmail: false,
                publicGender: false,
                publicPhone: false,
                publicDob: false,
            },
        },
        sync: false,
        syncID: null,
        unsent: false,
        urlsPreview: null,
    },

    {
        id: "d3576bc0-f13e-4c40-a7ed-7e00559ce300",
        type: MessageType.MESSAGE,
        message: "hello?",
        subMessage: null,
        iconMessage: null,
        messageOnRightSide: false,
        consecutiveMessages: true,
        timeOfMessageSentDisplay: "11/08/2024 14:30",
        edited: false,
        makerDate: "Fri Jun 17 2022 11:27:28 GMT+0100",
        recordStatus: null,
        channelID: "f4536349-e139-4eae-b3e1-4811f9cc6329",
        reply: null,
        attachments: null,
        messageReactions: null,
        user: {
            id: "42b73dae-321f-4258-a604-afad0839b11f",
            fullName: "Taylor swift",
            avatar: "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            online: true,
            coverPhoto:
                "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            gender: "Female",
            dob: "1723362246",
            phone: "0987654321",
            email: "taylor.swift@gmail.com",
            countryCode: "+1",
            languageCode: "en",
            setting: {
                publicEmail: false,
                publicGender: false,
                publicPhone: false,
                publicDob: false,
            },
        },
        sync: false,
        syncID: null,
        unsent: false,
        urlsPreview: null,
    },

    {
        id: "2bad8592-dd7f-436a-b7ae-b928ee1c77bb",
        type: MessageType.MESSAGE,
        message: "hi",
        subMessage: null,
        iconMessage: null,
        messageOnRightSide: true,
        consecutiveMessages: true,
        timeOfMessageSentDisplay: "11/08/2024 14:40",
        edited: false,
        makerDate: "Fri Jun 17 2022 11:27:28 GMT+0100",
        recordStatus: null,
        channelID: "f4536349-e139-4eae-b3e1-4811f9cc6329",
        reply: null,
        attachments: null,
        messageReactions: [
            {
                icon: "👍",
                quantity: 1,
                toOwn: true,
            },
        ],
        user: {
            id: "4c0b8918-edd9-4c8e-9eac-ea9769c98aae",
            fullName: "Phạm Việt Tú",
            avatar: "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
            online: true,
            coverPhoto:
                "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
            gender: "Male",
            dob: "1723362246",
            phone: "0987654321",
            email: "phamviettu3009@gmail.com",
            countryCode: "+84",
            languageCode: "vi",
            setting: {
                publicEmail: false,
                publicGender: false,
                publicPhone: false,
                publicDob: false,
            },
        },
        sync: false,
        syncID: null,
        unsent: false,
        urlsPreview: null,
    },

    {
        id: "8be0a75c-c276-46ed-8bd2-2f6be5b2d4e7",
        type: MessageType.ATTACHMENTS,
        message: "soon",
        subMessage: null,
        iconMessage: null,
        messageOnRightSide: true,
        consecutiveMessages: true,
        timeOfMessageSentDisplay: "11/08/2024 14:50",
        edited: false,
        makerDate: "Fri Jun 17 2022 11:27:28 GMT+0100",
        recordStatus: null,
        channelID: "f4536349-e139-4eae-b3e1-4811f9cc6329",
        reply: {
            id: "2bad8592-dd7f-436a-b7ae-b928ee1c77bb",
            type: MessageType.MESSAGE,
            message: "soon",
            attachments: null,
        },
        attachments: [
            {
                id: "bdb716db-3cb2-4f8f-b1ce-8043fc969751",
                type: AttachmentType.IMAGE_TYPE,
            },
        ],
        messageReactions: null,
        user: {
            id: "4c0b8918-edd9-4c8e-9eac-ea9769c98aae",
            fullName: "Phạm Việt Tú",
            avatar: "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
            online: true,
            coverPhoto:
                "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
            gender: "Male",
            dob: "1723362246",
            phone: "0987654321",
            email: "phamviettu3009@gmail.com",
            countryCode: "+84",
            languageCode: "vi",
            setting: {
                publicEmail: false,
                publicGender: false,
                publicPhone: false,
                publicDob: false,
            },
        },
        sync: false,
        syncID: null,
        unsent: false,
        urlsPreview: null,
    },

    {
        id: "d43238e3-1e8a-4627-b4c5-2ccef50a6daa",
        type: MessageType.ATTACHMENTS,
        message: "soon 1",
        subMessage: null,
        iconMessage: null,
        messageOnRightSide: true,
        consecutiveMessages: true,
        timeOfMessageSentDisplay: "11/08/2024 14:50",
        edited: true,
        makerDate: "Fri Jun 17 2022 11:27:28 GMT+0100",
        recordStatus: null,
        channelID: "f4536349-e139-4eae-b3e1-4811f9cc6329",
        reply: {
            id: "2bad8592-dd7f-436a-b7ae-b928ee1c77bb",
            type: MessageType.MESSAGE,
            message: "soon",
            attachments: [
                {
                    id: "bdb716db-3cb2-4f8f-b1ce-8043fc969751",
                    type: AttachmentType.IMAGE_TYPE,
                },
            ],
        },
        attachments: [
            {
                id: "2b0cba48-b2ba-45fd-a293-172ca530eb01",
                type: AttachmentType.IMAGE_TYPE,
            },
            {
                id: "2b0cba48-b2ba-45fd-a293-172ca530eb02",
                type: AttachmentType.IMAGE_TYPE,
            },
            {
                id: "2b0cba48-b2ba-45fd-a293-172ca530eb03",
                type: AttachmentType.IMAGE_TYPE,
            },
            {
                id: "2b0cba48-b2ba-45fd-a293-172ca530eb04",
                type: AttachmentType.IMAGE_TYPE,
            },
            {
                id: "2b0cba48-b2ba-45fd-a293-172ca530eb05",
                type: AttachmentType.IMAGE_TYPE,
            },
            {
                id: "2b0cba48-b2ba-45fd-a293-172ca530eb06",
                type: AttachmentType.IMAGE_TYPE,
            },
            {
                id: "2b0cba48-b2ba-45fd-a293-172ca530eb07",
                type: AttachmentType.IMAGE_TYPE,
            },
            {
                id: "2b0cba48-b2ba-45fd-a293-172ca530eb08",
                type: AttachmentType.IMAGE_TYPE,
            },
        ],
        messageReactions: [
            {
                icon: "👍",
                quantity: 2,
                toOwn: true,
            },
        ],
        user: {
            id: "4c0b8918-edd9-4c8e-9eac-ea9769c98aae",
            fullName: "Phạm Việt Tú",
            avatar: "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
            online: true,
            coverPhoto:
                "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
            gender: "Male",
            dob: "1723362246",
            phone: "0987654321",
            email: "phamviettu3009@gmail.com",
            countryCode: "+84",
            languageCode: "vi",
            setting: {
                publicEmail: false,
                publicGender: false,
                publicPhone: false,
                publicDob: false,
            },
        },
        sync: false,
        syncID: null,
        unsent: false,
        urlsPreview: null,
    },

    {
        id: "d3576bc0-f13e-4c40-a7ed-7e00559ce33u",
        type: MessageType.ATTACHMENTS,
        message: "hello bla bala",
        subMessage: null,
        iconMessage: null,
        messageOnRightSide: false,
        consecutiveMessages: false,
        timeOfMessageSentDisplay: "11/08/2024 14:30",
        edited: false,
        makerDate: "Fri Jun 17 2022 11:27:28 GMT+0100",
        recordStatus: null,
        channelID: "f4536349-e139-4eae-b3e1-4811f9cc6329",
        reply: {
            id: "2bad8592-dd7f-436a-b7ae-b928ee1c77bb",
            type: MessageType.MESSAGE,
            message: "soon",
            attachments: [
                {
                    id: "bdb716db-3cb2-4f8f-b1ce-8043fc969751",
                    type: AttachmentType.IMAGE_TYPE,
                },
            ],
        },
        attachments: [
            {
                id: "2b0cba48-b2ba-45fd-a293-172ca530eb01",
                type: AttachmentType.IMAGE_TYPE,
            },
        ],
        messageReactions: [
            {
                icon: "👍",
                quantity: 1,
                toOwn: false,
            },
        ],
        user: {
            id: "42b73dae-321f-4258-a604-afad0839b11f",
            fullName: "Taylor swift",
            avatar: "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            online: true,
            coverPhoto:
                "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            gender: "Female",
            dob: "1723362246",
            phone: "0987654321",
            email: "taylor.swift@gmail.com",
            countryCode: "+1",
            languageCode: "en",
            setting: {
                publicEmail: false,
                publicGender: false,
                publicPhone: false,
                publicDob: false,
            },
        },
        sync: false,
        syncID: null,
        unsent: false,
        urlsPreview: ["https://www.youtube.com/watch?v=dQw4w9WgXcQ"],
    },

    {
        id: "d3576bc0-f13e-4c40-a7ed-7e00559ce307",
        type: MessageType.ICON_MESSAGE,
        message: "",
        subMessage: "Delete for all",
        iconMessage: "👍",
        messageOnRightSide: false,
        consecutiveMessages: false,
        timeOfMessageSentDisplay: "11/08/2024 14:30",
        edited: false,
        makerDate: "Fri Jun 17 2022 11:27:28 GMT+0100",
        recordStatus: MessageRecordStatus.DELETE,
        channelID: "f4536349-e139-4eae-b3e1-4811f9cc6329",
        reply: null,
        attachments: null,
        messageReactions: null,
        user: {
            id: "42b73dae-321f-4258-a604-afad0839b11f",
            fullName: "Taylor swift",
            avatar: "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            online: true,
            coverPhoto:
                "https://upload.wikimedia.org/wikipedia/commons/9/91/Taylor_Swift_at_the_Golden_Globes_2024_%28Enhanced%2C_cropped%29_1.jpg",
            gender: "Female",
            dob: "1723362246",
            phone: "0987654321",
            email: "taylor.swift@gmail.com",
            countryCode: "+1",
            languageCode: "en",
            setting: {
                publicEmail: false,
                publicGender: false,
                publicPhone: false,
                publicDob: false,
            },
        },
        sync: false,
        syncID: null,
        unsent: false,
        urlsPreview: null,
    },
];
